name: Merge plttn/tide main into fork/plttn

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork/plttn
        uses: actions/checkout@v4
        with:
          ref: fork/plttn
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/plttn/tide.git
          git fetch upstream main

      - name: Merge upstream/main
        run: |
          git checkout fork/plttn
          git merge upstream/main --no-ff -m "Merge plttn/tide main into fork/plttn"

      - name: Push merge commit
        run: git push origin fork/plttn
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
